# Generated by Django 4.0.3 on 2022-08-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile',
            name='vip',
            field=models.BooleanField(default=True),
        ),
    ]
