# Generated by Django 4.0.3 on 2022-08-04 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0002_automobile_sold'),
        ('inventory_rest', '0002_automobile_vip'),
    ]

    operations = [
    ]
